export const ABOUT_ME_TEXT = 'I am a proficient Javascript developer with a strong grasp of modern frontend technologies with hands on industry experience in building and shipping productions ready web and mobile apps with React and React Native. I specialize in building dynamic and responsive user interfaces, leveraging components and state management for seamless user experiences. My expertise includes integrating APIs, optimizing performance, and ensuring code maintainability through modular design. With a passion for creating intuitive and visually appealing  applications, I have contributed to collaborative development teams, consistently delivering high-quality code that meets user needs and industry standards.'

export const SKILLS = [
  "Javascript",
  "Typescript",
  "Nodejs",
  "React",
  "Nextjs",
  "Redux",
  "React Query",
  "Tailwind CSS",
  "React Native",
  "Expo",
  "Git",
  "Sqlite DB",
  "Mongo DB",
  "Docker",
  "Cloudflare",
  "Amazon AWS",
  "Xcode",
  "Android Studio",
];

export const EXPERIENCE = [
 {
    company: "Studio Frontier",
    companyURL: "https://studiofrontier.com",
    role: "Software Developer",
    startDate: "July 2024",
    endDate: "Present",
    projects: [
      {
        id: 1,
        isLive: false,
        isWebLive: false,
        webURL: "",
        appURL: "",
        name: "Upstox",
        status: "Production",
        industry: "Trading and Investing",
        techStack: [
          "React Native",
          "Typescript",
          "React Native Reanimated",
          "Storybook",
          "Jenkins",
        ],
        contributions: [
          "Built a scalable, high-performance frontend for Upstox, a widely used trading and investing platform serving millions of users across India.",
          "Built UI components for NPS (National Pension Scheme), including BottomSheets, and fixed bugs.",
          "Implemented deep links for NPS (in-app) and Bonds/FD (mobile to web).",
          "Integrated dark mode across the app and UI library.",
          "Developed and shipped an improved snackbar component (Snackbar v2), now in production.",
          "Built a scalable, high-performance Portfolio Widget for Mutual Funds, Gold, and HomeScreen.",
          "Added a custom patch for LineChart as per product requirements for Native Android Fix.",
        ],
      },
      {
        id: 2,
        isLive: false,
        isWebLive: false,
        webURL: "",
        appURL: "",
        name: "Haseed",
        status: "Prototype",
        industry: "Goal-based Investment",
        techStack: [
          "React Native",
          "Typescript",
          "React Native Reanimated",
        ],
        contributions: [
          "Developed a prototype for Haseed, a goal-based investment app, leveraging React Native Reanimated for smooth and dynamic animations.",
        ],
      },
    ],
  },
  {
    company: "Heisentech Solutions",
    companyURL: "https://heisentech.com",
    role: "JavaScript Developer - React & React Native",
    startDate: "July 2022",
    endDate: "July 2024",
    projects: [
      {
        id: 1,
        isLive: true,
        isWebLive: false,
        webURL: "",
        appURL:
          "https://apps.apple.com/in/app/dreamlyzer-dream-analysis/id6474172301",
        name: "Dreamlyzer: Dream Analysis (iOS App)",
        status: "Production",
        industry: "Lifestyle",
        techStack: [
          "React Native",
          "Typescript",
          "React Navigation",
          "OpenAI",
          "React Native SQLite DB",
          "RevenueCat",
          "React Native Reanimated",
          "Cloudflare (Workers and KV Storage)",
        ],
        contributions: [
          "Solo Development: Successfully built the app single-handedly.",
          "Integration of OpenAI APIs for advanced dream analysis features.",
          "Implemented in-app subscriptions using RevenueCat.",
          "Leveraged React Navigation and React Native Reanimated for smooth navigation and high-performance animations.",
          "Deployed Cloudflare Workers and KV Storage for efficient backend operations.",
          "Utilized React Native SQLite DB for local data storage and offline capabilities.",
        ],
      },
      {
        id: 2,
        isLive: false,
        appURL: "",
        isWebLive: false,
        webURL: "",
        name: "River - (iOS & Android)",
        status: "Beta Mode",
        industry: "Payment Diary App for SMEs",
        techStack: [
          "React Native",
          "Typescript",
          "React Navigation",
          "React Native Google SignIn",
          "SQLite DB",
          "Google Sheets API",
        ],
        contributions: [
          "Built elegant and responsive screens and components.",
          "Created multiple APIs using Google Sheets API for invoice management.",
          "Transitioned the entire database from Supabase to Google Sheets.",
          "Integrated Google Sheets APIs into the application.",
          "Implemented React Native SQLite DB for offline data management.",
          "Transitioned authentication from Supabase to React Native Google SignIn.",
          "Actively debugged and resolved issues, contributing to feature planning.",
        ],
      },
      {
        id: 3,
        isLive: false,

        isWebLive: false,
        webURL: "",
        appURL: "",
        name: "Hawkeye (iOS & Android)",
        status: "Beta Mode",
        industry: "Photo Sharing App",
        techStack: [
          "React Native",
          "Typescript",
          "React Navigation",
          "Supabase",
          "AWS Face Rekognition",
          "DynamoDB",
          "AWS S3 Bucket",
          "SQLite DB",
        ],
        contributions: [
          "Configured and set up React Navigation.",
          "Developed various screens ensuring UI consistency.",
          "Integrated AWS Face Rekognition for facial recognition and liveness detection.",
          "Incorporated biometric authentication features.",
          "Integrated backend APIs for face verification, password sharing, and accessing galleries.",
          "Implemented features for downloading photos from AWS S3 Bucket.",
          "Contributed to UI optimization for efficient rendering and smooth transitions.",
          "Collaborated with backend developers for seamless integration.",
        ],
      },
      {
        id: 4,
        isLive: false,
        isWebLive: false,
        webURL: "",
        appURL: "",
        name: "VivDesk - (web)",
        status: "Beta Mode",
        industry: "Customer-engagement SaaS platform",
        techStack: [
          "React",
          "NextJS",
          "Typescript",
          "TailwindCSS",
          "Supabase",
          "Supabase Auth",
          "WhatsApp APIs",
        ],
        contributions: [
          "Participated in designing the database schema and planning the overall tech stack for the application.",
          "Built a dynamic and responsive chat page to enhance customer engagement and user interaction.",
          "Developed multiple reusable components, streamlining development and ensuring consistency across various pages.",
          "Integrated backend APIs to connect frontend features with server-side functionalities, and resolved bugs and issues to improve app stability.",
        ],
      },
      {
        id: 5,
        isLive: false,
        isWebLive: true,
        webURL: "https://blogs.heisentech.com",
        appURL: "",
        name: "Company's Blog Site",
        status: "Deployed",
        industry: "Blogs",
        techStack: [
          "React",
          "NextJS",
          "Typescript",
          "TailwindCSS",
          "MDX",
          "SendInBlue",
        ],
        contributions: [
          "Designed and developed the blog website with a modern, responsive layout.",
          "Integrated MDX for easy content management and customization.",
          "Used NextJS for optimized performance and fast loading times.",
          "Implemented email subscription functionality with SendInBlue.",
        ],
      },
    ],
  },
  {
    company: "Lucien Solutions",
    companyURL: "https://luciensolutions.com/",
    role: "Frontend Developer",
    startDate: "June 2022",
    endDate: "July 2022",
    projects: [
      {
        id: 5,
        isLive: false,
        isWebLive: false,
        webURL: "",
        appURL: "",
        name: "My Moholla",
        status: "Production",
        industry: "Society Management",
        techStack: [
          "React",
          "React Router",
          "Typescript",
          "Material UI",
          "AWS Lambda",
        ],
        contributions: [
          "Refactored a purchased ReactJS template, removing unused code and organizing components to improve maintainability and readability.",
          "Integrated File Upload APIs for PDFs and documents, ensuring seamless user uploads with validation, error handling, and secure backend storage.",
          "Revamped routes and components, implementing new styles to align with company branding and design guidelines, enhancing the user experience.",
          "Managed a team member by setting clear project requirements, providing regular feedback, and facilitating their professional growth through knowledge-sharing sessions.",
        ],
      },
    ],
  },
  {
    company: "Freelancing",
    companyURL: "https://luciensolutions.com/",
    role: "Software Developer",
    startDate: "Jan 2022",
    endDate: "May 2022",
    projects: [
      {
        id: 1,
        isLive: false,
        isWebLive: true,
        webURL: "https://restaurant-app-mu.vercel.app",
        appURL: "",
        name: "Food Ordering Web App",
        status: "Production",
        industry: "Food Ordering",
        techStack: ["React.js", "Next.js", "Material UI", "Firebase"],
        contributions: [
          "Built a food ordering web app using React.js and Material UI with an agile approach.",
          "Integrated Firebase for real-time order processing and database management.",
          "Collaborated closely with the client, actively seeking and implementing their feedback.",
        ],
      },
    ],
  },
 
];
