import { Experience } from "@/types";

export const ABOUT_ME_TEXT =
  "Senior Software Engineer with 4+ years of experience building production-grade web and mobile applications across fintech, AI, creator economy, and SaaS. I specialize in designing scalable systems, leading product development, and shipping reliable software using React, React Native, Next.js, TypeScript, and modern cloud technologies. Beyond writing code, I enjoy solving product problems, designing maintainable architectures, improving developer experience, and leveraging AI to accelerate software delivery. I believe great engineering is about making the right technical decisions, building for scale, and creating products that users genuinely enjoy using.";

export const SKILLS = [
  "React",
  "React Native",
  "TypeScript",
  "JavaScript",
  "Next.js",
  "Expo",
  "Node.js",
  "NestJS",
  "Redux Toolkit",
  "TanStack Query",
  "Zustand",
  "Expo Router",
  "REST APIs",
  "OpenAI APIs",
  "Vercel AI SDK",
  "Server-Driven UI",
  "Tailwind CSS",
  "NativeWind",
  "Firebase",
  "Supabase",
  "SQLite",
  "MongoDB",
  "AWS",
  "Cloudflare",
  "Docker",
  "Git",
  "CI/CD",
  "EAS Build",
  "Xcode",
  "Android Studio",
];

export const EXPERIENCE: Experience[] = [
  {
    company: "Geekyants",
    companyURL: "https://geekyants.com",
    logo: "/logo/geekyants-logo.jpeg",
    role: "Senior Software Engineer 2",
    startDate: "April 2026",
    endDate: "Present",
    projects: [
      {
        id: 1,
        isLive: false,
        isWebLive: false,
        webURL: "",
        appURL: "",
        name: "AI-Powered Server-Driven UI Framework",
        status: "Internal Project",
        industry: "Developer Platform / AI",
        techStack: [
          "React Native",
          "Expo",
          "TypeScript",
          "Vercel AI SDK",
          "NestJS",
          "OpenAI",
          "Zod",
          "Zustand",
        ],
        contributions: [
          "Architected and developed a Server-Driven UI (SDUI) framework for React Native, enabling screens to be rendered dynamically from backend JSON configurations.",
          "Built a scalable component registry with reusable UI components, dynamic forms, validation, navigation, and state management.",
          "Integrated the Vercel AI SDK to generate SDUI JSON dynamically using LLMs, enabling AI-driven UI generation.",
          "Designed the framework to support rapid feature delivery without requiring mobile app updates for UI changes.",
          "Defined a modular architecture focused on extensibility, maintainability, and developer experience.",
        ],
      },
      {
        id: 2,
        isLive: true,
        isWebLive: false,
        webURL: "https://www.talenzap.com/",
        iOSURL: "https://apps.apple.com/in/app/talenzap/id6756573930",
        androidURL:
          "https://play.google.com/store/apps/details?id=com.talenzap.mobileapp",
        appURL: "",
        name: "Talenzap",
        status: "Production",
        industry: "Creator Economy & Social Entertainment",
        techStack: [
          "Monorepo",
          "React Native",
          "Expo",
          "TypeScript",
          "Expo Router",
          "Next.js",
          "Tailwind CSS",
          "zustand",
          "React Query",
          "NestJS",
          "FCM",
          "EAS",
          "Firebase Crashlytics",
          "Jenkins",
          "Docker",
          "Grafana",
        ],
        contributions: [
          "Leading the Talenzap mobile application as Tech Lead, driving technical architecture, feature development, and release planning.",
          "Own end-to-end mobile delivery, from feature implementation and code reviews to production deployments on the App Store and Google Play.",
          "Established CI/CD pipelines using Expo EAS for automated builds, submissions, and environment-based deployments.",
          "Designed scalable application architecture with reusable components, state management, and API integrations.",
          "Implemented analytics, crash reporting, push notifications, and production monitoring to improve application reliability.",
          "Collaborate closely with product, design, QA, and backend teams to deliver production-ready features and improve developer workflows.",
        ],
      },
    ],
  },
  {
    company: "Studio Frontier",
    companyURL: "https://studiofrontier.com",
    logo: "/logo/studio-frontier-logo.jpeg",
    role: "Software Developer",
    startDate: "July 2024",
    endDate: "July 2025",
    projects: [
      {
        id: 1,
        isLive: true,
        isWebLive: false,
        webURL: "",
        iOSURL:
          "https://apps.apple.com/in/app/upstox-demat-stock-mf-ipo/id1584953620",
        androidURL:
          "https://play.google.com/store/apps/details?id=in.upstox.app",
        appURL: "",
        name: "Upstox",
        status: "Production",
        industry: "Trading and Investing",
        techStack: [
          "React Native",
          "Typescript",
          "React Native Reanimated",
          "Storybook",
          "Jenkins",
        ],
        contributions: [
          "Built a scalable, high-performance frontend for Upstox, a widely used trading and investing platform serving millions of users across India.",
          "Built UI components for NPS (National Pension Scheme), including BottomSheets, and fixed bugs.",
          "Implemented deep links for NPS (in-app) and Bonds/FD (mobile to web).",
          "Integrated dark mode across the app and UI library.",
          "Developed and shipped an improved snackbar component (Snackbar v2), now in production.",
          "Built a scalable, high-performance Portfolio Widget for Mutual Funds, Gold, and HomeScreen.",
          "Added a custom patch for LineChart as per product requirements for Native Android Fix.",
        ],
      },
      {
        id: 3,
        isLive: false,
        isWebLive: false,
        webURL: "",
        appURL: "",
        name: "Synapse (Web App)",
        status: "Prototype",
        industry: "Stealth Fintech",
        techStack: ["Next.js", "Typescript", "shadcn/ui", "Tailwind CSS"],
        contributions: [
          "Built complex, responsive UI tables and screens using shadcn and Tailwind CSS.",
          "Engineered frontend architecture for a robust derivates trading web platform prototype.",
          "Implemented modular, reusable components with clean state management.",
        ],
      },
      {
        id: 4,
        isLive: false,
        isWebLive: false,
        webURL: "",
        appURL: "",
        name: "Confx",
        status: "Beta Mode",
        industry: "Events and Discovery",
        techStack: ["React Native", "Typescript", "NativeWind"],
        contributions: [
          "Developed the entire mobile app UI for iOS and Android using NativeWind and React Native.",
          "Built screens and reusable components with a focus on performance and UX.",
          "Integrated event discovery, favorites, and authentication features.",
        ],
      },
      {
        id: 5,
        isLive: false,
        isWebLive: false,
        webURL: "",
        appURL: "",
        name: "Echovaren",
        status: "Prototype",
        industry: "Voice Notes",
        techStack: ["Swift", "Cursor AI"],
        contributions: [
          "Built a prototype iOS app inspired by voicenotes.com using Swift and Cursor AI.",
          "Implemented voice recording, transcription, and simple note management features.",
          "Focused on performance, intuitive UX, and minimal design for quick note capture.",
        ],
      },
    ],
  },
  {
    company: "Heisentech Solutions",
    companyURL: "https://heisentech.com",
    logo: "/logo/heisentech-logo.jpeg",
    role: "JavaScript Developer - React & React Native",
    startDate: "July 2022",
    endDate: "July 2024",
    projects: [
      {
        id: 1,
        isLive: true,
        isWebLive: false,
        webURL: "",
        iOSURL:
          "https://apps.apple.com/in/app/dreamlyzer-dream-analysis/id6474172301",
        androidURL: "",
        appURL: "",
        name: "Dreamlyzer: Dream Analysis (iOS App)",
        status: "Production",
        industry: "Lifestyle",
        techStack: [
          "React Native",
          "Typescript",
          "React Navigation",
          "OpenAI",
          "React Native SQLite DB",
          "RevenueCat",
          "React Native Reanimated",
          "Cloudflare (Workers and KV Storage)",
        ],
        contributions: [
          "Solo Development: Successfully built the app single-handedly.",
          "Integration of OpenAI APIs for advanced dream analysis features.",
          "Implemented in-app subscriptions using RevenueCat.",
          "Leveraged React Navigation and React Native Reanimated for smooth navigation and high-performance animations.",
          "Deployed Cloudflare Workers and KV Storage for efficient backend operations.",
          "Utilized React Native SQLite DB for local data storage and offline capabilities.",
        ],
      },
      {
        id: 2,
        isLive: false,
        appURL: "",
        isWebLive: false,
        webURL: "",
        name: "River - (iOS & Android)",
        status: "Beta Mode",
        industry: "Payment Diary App for SMEs",
        techStack: [
          "React Native",
          "Typescript",
          "React Navigation",
          "React Native Google SignIn",
          "SQLite DB",
          "Google Sheets API",
        ],
        contributions: [
          "Built elegant and responsive screens and components.",
          "Created multiple APIs using Google Sheets API for invoice management.",
          "Transitioned the entire database from Supabase to Google Sheets.",
          "Integrated Google Sheets APIs into the application.",
          "Implemented React Native SQLite DB for offline data management.",
          "Transitioned authentication from Supabase to React Native Google SignIn.",
          "Actively debugged and resolved issues, contributing to feature planning.",
        ],
      },
      {
        id: 3,
        isLive: false,

        isWebLive: false,
        webURL: "",
        appURL: "",
        name: "Hawkeye (iOS & Android)",
        status: "Beta Mode",
        industry: "Photo Sharing App",
        techStack: [
          "React Native",
          "Typescript",
          "React Navigation",
          "Supabase",
          "AWS Face Rekognition",
          "DynamoDB",
          "AWS S3 Bucket",
          "SQLite DB",
        ],
        contributions: [
          "Configured and set up React Navigation.",
          "Developed various screens ensuring UI consistency.",
          "Integrated AWS Face Rekognition for facial recognition and liveness detection.",
          "Incorporated biometric authentication features.",
          "Integrated backend APIs for face verification, password sharing, and accessing galleries.",
          "Implemented features for downloading photos from AWS S3 Bucket.",
          "Contributed to UI optimization for efficient rendering and smooth transitions.",
          "Collaborated with backend developers for seamless integration.",
        ],
      },
      {
        id: 4,
        isLive: false,
        isWebLive: false,
        webURL: "",
        appURL: "",
        name: "VivDesk - (web)",
        status: "Beta Mode",
        industry: "Customer-engagement SaaS platform",
        techStack: [
          "React",
          "NextJS",
          "Typescript",
          "TailwindCSS",
          "Supabase",
          "Supabase Auth",
          "WhatsApp APIs",
        ],
        contributions: [
          "Participated in designing the database schema and planning the overall tech stack for the application.",
          "Built a dynamic and responsive chat page to enhance customer engagement and user interaction.",
          "Developed multiple reusable components, streamlining development and ensuring consistency across various pages.",
          "Integrated backend APIs to connect frontend features with server-side functionalities, and resolved bugs and issues to improve app stability.",
        ],
      },
      {
        id: 5,
        isLive: false,
        isWebLive: true,
        webURL: "https://blogs.heisentech.com",
        appURL: "",
        name: "Company's Blog Site",
        status: "Deployed",
        industry: "Blogs",
        techStack: [
          "React",
          "NextJS",
          "Typescript",
          "TailwindCSS",
          "MDX",
          "SendInBlue",
        ],
        contributions: [
          "Designed and developed the blog website with a modern, responsive layout.",
          "Integrated MDX for easy content management and customization.",
          "Used NextJS for optimized performance and fast loading times.",
          "Implemented email subscription functionality with SendInBlue.",
        ],
      },
    ],
  },
  {
    company: "Lucien Solutions",
    companyURL: "https://luciensolutions.com/",
    logo: "/logo/lucien-logo.jpeg",
    role: "Frontend Developer",
    startDate: "June 2022",
    endDate: "July 2022",
    projects: [
      {
        id: 5,
        isLive: false,
        isWebLive: false,
        webURL: "",
        appURL: "",
        name: "My Moholla",
        status: "Production",
        industry: "Society Management",
        techStack: [
          "React",
          "React Router",
          "Typescript",
          "Material UI",
          "AWS Lambda",
        ],
        contributions: [
          "Refactored a purchased ReactJS template, removing unused code and organizing components to improve maintainability and readability.",
          "Integrated File Upload APIs for PDFs and documents, ensuring seamless user uploads with validation, error handling, and secure backend storage.",
          "Revamped routes and components, implementing new styles to align with company branding and design guidelines, enhancing the user experience.",
          "Managed a team member by setting clear project requirements, providing regular feedback, and facilitating their professional growth through knowledge-sharing sessions.",
        ],
      },
    ],
  },
  {
    company: "Freelancing",
    companyURL: "https://luciensolutions.com/",
    role: "Software Developer",
    startDate: "Jan 2022",
    endDate: "May 2022",
    projects: [
      {
        id: 1,
        isLive: false,
        isWebLive: true,
        webURL: "https://restaurant-app-mu.vercel.app",
        appURL: "",
        name: "Food Ordering Web App",
        status: "Production",
        industry: "Food Ordering",
        techStack: ["React.js", "Next.js", "Material UI", "Firebase"],
        contributions: [
          "Built a food ordering web app using React.js and Material UI with an agile approach.",
          "Integrated Firebase for real-time order processing and database management.",
          "Collaborated closely with the client, actively seeking and implementing their feedback.",
        ],
      },
    ],
  },
];
